### ISSUE TITLE
FYI: Good Design Principals from Class 

### ISSUE THREAD

**Issue by mattbanach** [mattbanach/cs422_ctatransit#4]
The professor spent some time covering this stuff, that will be expected in our software.
- Clarity
    - Buttons should look like buttons.
    - Not too much information on the home page.
    - Self-Explainitory, Good use of headings
    - Pay attention to layout, colors, navigation.
    - This is all Krug
- Constancy 
    - Norman is really big on this.
- Feedback
    - The user should get a sense of what they are doing.
    - Show progress indicators as necessary 

Expectations: Answer these questions
- What is this site for?
- What can I do here?
- How can I contact the owner?

**Comment by mpatterson2100** [comment]
1) This site is for transit engineers
2) Since our "site" is one page, what you can do is defined at a particular
pane.
3) You can contact the owner by clicking on the about button that we will
add, and the contact button.

On Fri, Mar 13, 2015 at 10:43 AM, mattbanach <notifications@github.com>
wrote:

> The professor spent some time covering this stuff, that will be expected
> in our software.
>
>    - Clarity
>       - Buttons should look like buttons.
>       - Not too much information on the home page.
>       - Self-Explainitory, Good use of headings
>       - Pay attention to layout, colors, navigation.
>       - This is all Krug
>     - Constancy
>       - Norman is really big on this.
>     - Feedback
>       - The user should get a sense of what they are doing.
>       - Show progress indicators as necessary
>
> Expectations: Answer these questions
>
>    - What is this site for?
>    - What can I do here?
>    - How can I contact the owner?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattbanach/cs422_ctatransit/issues/4>.
>



-- 
Matthew Patterson
